package smartmeters;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import org.aeonbits.owner.ConfigFactory;
import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.core.server.resources.CoapExchange;

import static org.eclipse.californium.core.coap.CoAP.ResponseCode.*;
import static org.eclipse.californium.core.coap.CoAP.ResponseCode.DELETED;
import static org.eclipse.californium.core.coap.CoAP.ResponseCode.NOT_ACCEPTABLE;
import static org.eclipse.californium.core.coap.MediaTypeRegistry.TEXT_PLAIN;

import madkit.kernel.Madkit;
import madkit.kernel.AgentAddress;
import madkit.kernel.Message;

import smartmeters.TestimonialStore;

/**
 * Created by nikolay on 19.02.15.
 */

public class SubscribeHub extends CoapResource {

    // singleton to store data, generated by agents
    private TestimonialStore store = TestimonialStore.getInstance();
    private SmartMetersConfig simulationConfig  = ConfigFactory.create(SmartMetersConfig.class);

    private Timer timer;

    public SubscribeHub() {
        super("subscribe");

        setObservable(true);
        getAttributes().setTitle("Simple CoAP handler to observe third-party state change");
        getAttributes().addResourceType("observe");
        getAttributes().setObservable();
        setObserveType(CoAP.Type.CON);

        timer = new Timer();
        timer.schedule(new TimeTask(), 0, simulationConfig.meters_heartbeat());
    }

    private class TimeTask extends TimerTask {
        @Override
        public void run() {
            changed();
        }
    }

    @Override
    public void handleGET(CoapExchange exchange) {
        exchange.setMaxAge(simulationConfig.coap_ttl());
        exchange.respond(CONTENT, store.getData(), TEXT_PLAIN);
    }

    @Override
    public void handleDELETE(CoapExchange exchange) {
        clearAndNotifyObserveRelations(NOT_FOUND);
        exchange.respond(DELETED);
        timer.cancel();
    }

}
